# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'queued'), (1, 'sent'), (2, 'delivered'), (3, 'errored')])),
            ],
        ),
    ]
